mininvim.deps.setup({
  { source = 'plugins.mini.sessions' },
  { source = 'plugins.mini.notify', disable = true },
  { source = 'plugins.mini.starter', disable = false },
  { source = 'plugins.mini.icons' },
  { source = 'plugins.mini.basics' },
  { source = 'mini.colors', later = true, opts = {} },
  { source = 'mini.keymap', later = true, opts = {} },
  { source = 'plugins.mini.animate', later = true },
  { source = 'plugins.mini.bracketed', later = true },
  { source = 'plugins.mini.surround', later = true },
  { source = 'plugins.mini.jump', later = true },
  { source = 'plugins.mini.pairs', later = true },
  { source = 'plugins.mini.cursorword', later = true },
  { source = 'mini.trailspace', later = true, opts = {} },
  { source = 'mini.fuzzy', later = true, opts = {} },
  { source = 'mini.extra', later = true, opts = {} },
  { source = 'mini.operators', later = true, opts = {} },
  { source = 'mini.move', later = true, opts = {} },
  { source = 'mini.bufremove', later = true, opts = {} },
  { source = 'plugins.mini.comment', later = true },
  { source = 'plugins.mini.misc', later = true },
  { source = 'plugins.mini.snippets', later = true },
  { source = 'plugins.mini.jump2d', later = true },
  { source = 'plugins.mini.tabline', later = true, disable = false },
  { source = 'plugins.mini.pick', later = true, disable = false },
  { source = 'plugins.mini.diff', later = true, disable = false },
  { source = 'plugins.mini.git', later = true },
  { source = 'plugins.mini.ai', later = true },
  { source = 'plugins.mini.indentscope', later = true, disable = true },
  { source = 'plugins.mini.hipatterns', later = true },
  { source = 'plugins.mini.minimap', later = true },
  {
    source = 'plugins.mini.files',
    later = false,
    disable = false,
  },
  {
    source = 'plugins.mini.clues',
  },
  {
    source = 'plugins.mini.visited',
    later = true,
    disable = false,
  },
})
